### ISSUE TITLE
How do I use this plugin to load images for hover effects?

### ISSUE THREAD

**Issue by simkimsia** [alexanderdickson/waitForImages#35]
I am not using css sprites.

So what happens is that my css code is:

``` css
.button_48x49_img {
    width: 48px;
    height: 49px;
}

.button_join_login_48x49_img {
    background-image: url('a.png');
}

.button_join_login_48x49_img:hover {
    background-image: url('b.png');
}
```

when the user first hovers over the image, there will be a slight delay. Which subsequently, this delay is no more.

I was told to somehow load all the images in the `$(window).load()` function. 

How do I use this plugin to achieve this result?
