### ISSUE TITLE
Not Working if the element have background images set in different class

### ISSUE THREAD

**Issue by itsabhik** [alexanderdickson/waitForImages#67]
Here is the HTML markup..
```html
<div class="parent">
	<div class="item item-1"></item>
	<div class="item item-2"></item>
	<div class="item item-3"></item>
	<div class="item item-4"></item>
	<div class="preloader"></div>
</div>
```

jQuery
```javascript
jQuery( document ).ready(function( $ ) {
	$( '.item' ).waitForImages(function() {
		finished: function() {
			$('.preloader').fadeOut();
			$(this).fadeIn();
		},
		/*
		each: function() {
			$(this).fadeIn();
		},
		*/
		waitForAll: true,
	});
});
```

CSS
```css
.item{
	width: 500px;
	height: 200px;
}
.item-1{
  background-image: url("images/item-1");
}
.item-2{
  background-image: url("images/item-2");
}
.item-3{
  background-image: url("images/item-3");
}
.item-4{
  background-image: url("images/item-4");
}
.item-2, .item-3, .item-4{
  display: none;
}
```

It's not working, not even for the visible block.
